model:
  target: models.CRS_Diff.CRSControlNet
  params:
    linear_start: 0.0001
    linear_end: 0.02
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "hsi"
    cond_stage_key: "txt"
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215  # 0.18215
    use_ema: False
    mode: CRS

    local_control_config:
      target: models.local_adapter.LocalAdapter
      params:
        in_channels: 4
        model_channels: 320
        local_channels: 18
        inject_channels: [192, 256, 384, 512]
        inject_layers: [1, 4, 7, 10]
        num_res_blocks: 2
        attention_resolutions: [4, 2, 1]
        channel_mult: [1, 2, 4, 4]
        use_checkpoint: True
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        legacy: False

    global_content_control_config:
      target: models.global_adapter.GlobalContentAdapter
      params:
        in_dim: 768
        channel_mult: [2, 4]

    global_text_control_config:
      target: models.global_adapter.GlobalTextAdapter
      params:
        in_dim: 768

    metadata_config:
      target: models.metadata_embedding.metadata_embeddings
      params:
        max_value: 1000
        embedding_dim: 320
        metadata_dim: 7
        max_period: 10000


    unet_config:
      target: models.local_adapter.LocalControlUNetModel
      params:
        image_size: 32
        in_channels: 4
        model_channels: 320
        out_channels: 4
        num_res_blocks: 2
        attention_resolutions: [4, 2, 1]
        channel_mult: [1, 2, 4, 4]
        use_checkpoint: True
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 96
          resolution: 256
          in_channels: 48
          out_ch: 48
          ch: 64
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 4
          attn_resolutions: [16, 32, 64]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder



